#!/usr/bin/env bash

#
# Author: Kooper Smith
#
# Purpose:
#     Open a file with Notepad++
#       (from Git Bash)
#
# Arguments:
#     $1 = The file to open.
#

# The "&" prevents it from locking the terminal
npp.bat $1 &
