#!/usr/bin/env bash

#
# Author: Kooper Smith
#
# Purpose:
#     Open a file with Notepad++
#       (from Git Bash)
#
# Arguments:
#     $1 = The file to open.
#

# The "&" prevents it from locking the terminal
npp.bat $1 &

# check to see if NPP_DIR is set
#if [ -n ${NPP_DIR+x} ];
#then #if not, then use a default
#	NPP_DIR="/C/Program Files (x86)/Notepad++/"; 
#fi

# The & makes it run detached from the terminal.
#"$NPP_DIR/notepad++.exe" $1 &