#!/usr/bin/env bash

#
# Author: Kooper Smith
#
# Purpose:
#     Create a basic Maven project
#       (in Windows)
#
# Arguments:
#     <None>
#

ARCETYPE_GROUP_ID="pl.org.miki"
ARCETYPE_ARTIFACT_ID="java8-quickstart-archetype"
ARCETYPE_VERSION="1.0.0"

mvn archetype:generate \
 -DarchetypeGroupId=$ARCETYPE_GROUP_ID \
 -DarchetypeArtifactId=$ARCETYPE_ARTIFACT_ID \
 -DarchetypeVersion=$ARCETYPE_VERSION